// <auto-generated />
namespace MVCProject.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deaia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deaia));
        
        string IMigrationMetadata.Id
        {
            get { return "202203161851407_deaia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
