//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.WebUI.PTTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://accept.ptt.gov.tr", ConfigurationName="PTTService.LoadPortType")]
    public interface LoadPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHscodeList", ReplyAction="urn:getHscodeListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MVCProject.WebUI.PTTService.getHscodeListResponse getHscodeList(MVCProject.WebUI.PTTService.getHscodeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getHscodeList", ReplyAction="urn:getHscodeListResponse")]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.getHscodeListResponse> getHscodeListAsync(MVCProject.WebUI.PTTService.getHscodeListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:loadData", ReplyAction="urn:loadDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MVCProject.WebUI.PTTService.loadDataResponse loadData(MVCProject.WebUI.PTTService.loadDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:loadData", ReplyAction="urn:loadDataResponse")]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.loadDataResponse> loadDataAsync(MVCProject.WebUI.PTTService.loadDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class InputHscodeList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private System.Nullable<int> userNameField;
        
        private bool userNameFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userNameSpecified {
            get {
                return this.userNameFieldSpecified;
            }
            set {
                this.userNameFieldSpecified = value;
                this.RaisePropertyChanged("userNameSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class OutputBarcodeInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string barcodeURLField;
        
        private System.Nullable<int> faultCodeField;
        
        private bool faultCodeFieldSpecified;
        
        private string faultDescriptionField;
        
        private System.Nullable<bool> successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string barcodeURL {
            get {
                return this.barcodeURLField;
            }
            set {
                this.barcodeURLField = value;
                this.RaisePropertyChanged("barcodeURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool faultCodeSpecified {
            get {
                return this.faultCodeFieldSpecified;
            }
            set {
                this.faultCodeFieldSpecified = value;
                this.RaisePropertyChanged("faultCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string faultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("faultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("successSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OutputBarcodeInformation[] barcodeInformationField;
        
        private System.Nullable<int> faultCodeField;
        
        private bool faultCodeFieldSpecified;
        
        private string faultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("barcodeInformation", IsNullable=true, Order=0)]
        public OutputBarcodeInformation[] barcodeInformation {
            get {
                return this.barcodeInformationField;
            }
            set {
                this.barcodeInformationField = value;
                this.RaisePropertyChanged("barcodeInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool faultCodeSpecified {
            get {
                return this.faultCodeFieldSpecified;
            }
            set {
                this.faultCodeFieldSpecified = value;
                this.RaisePropertyChanged("faultCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string faultDescription {
            get {
                return this.faultDescriptionField;
            }
            set {
                this.faultDescriptionField = value;
                this.RaisePropertyChanged("faultDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class InvoceContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> countField;
        
        private bool countFieldSpecified;
        
        private string currencyField;
        
        private string originField;
        
        private string productHarmonyCodeField;
        
        private string productNameField;
        
        private string reserved1Field;
        
        private string reserved2Field;
        
        private string reserved3Field;
        
        private double unitPriceField;
        
        private bool unitPriceFieldSpecified;
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string productHarmonyCode {
            get {
                return this.productHarmonyCodeField;
            }
            set {
                this.productHarmonyCodeField = value;
                this.RaisePropertyChanged("productHarmonyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string reserved1 {
            get {
                return this.reserved1Field;
            }
            set {
                this.reserved1Field = value;
                this.RaisePropertyChanged("reserved1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string reserved2 {
            get {
                return this.reserved2Field;
            }
            set {
                this.reserved2Field = value;
                this.RaisePropertyChanged("reserved2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string reserved3 {
            get {
                return this.reserved3Field;
            }
            set {
                this.reserved3Field = value;
                this.RaisePropertyChanged("reserved3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitPriceSpecified {
            get {
                return this.unitPriceFieldSpecified;
            }
            set {
                this.unitPriceFieldSpecified = value;
                this.RaisePropertyChanged("unitPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class BarcodeInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string additionalDocumentsField;
        
        private string additionalServiceField;
        
        private string barcodeField;
        
        private InvoceContent[] contextField;
        
        private double desiField;
        
        private bool desiFieldSpecified;
        
        private string financialAdvisorNoField;
        
        private System.Nullable<int> heightField;
        
        private bool heightFieldSpecified;
        
        private string invoceNoField;
        
        private System.Nullable<int> lengthField;
        
        private bool lengthFieldSpecified;
        
        private double paymentConditionalPriceField;
        
        private bool paymentConditionalPriceFieldSpecified;
        
        private string paymentmethodField;
        
        private System.Nullable<int> postalAccountNumberField;
        
        private bool postalAccountNumberFieldSpecified;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private string receiverAdresField;
        
        private string receiverAdres2Field;
        
        private string receiverCityIDField;
        
        private string receiverCityID2Field;
        
        private string receiverCountryIdField;
        
        private string receiverCountryId2Field;
        
        private string receiverMailField;
        
        private string receiverMail2Field;
        
        private string receiverNameField;
        
        private string receiverName2Field;
        
        private string receiverPhoneField;
        
        private string receiverPhone2Field;
        
        private string receiverPostCodeField;
        
        private string receiverPostCode2Field;
        
        private string receiverSmsField;
        
        private string receiverSms2Field;
        
        private string reserved1Field;
        
        private string reserved10Field;
        
        private string reserved2Field;
        
        private string reserved3Field;
        
        private string reserved4Field;
        
        private string reserved5Field;
        
        private string reserved6Field;
        
        private string reserved7Field;
        
        private string reserved8Field;
        
        private string reserved9Field;
        
        private string returnReceiverAdresField;
        
        private string returnReceiverCityIDField;
        
        private string returnReceiverCountryIdField;
        
        private string returnReceiverDistrictIDField;
        
        private string returnReceiverMailField;
        
        private string returnReceiverNameField;
        
        private string returnReceiverPhoneField;
        
        private string returnReceiverPostCodeField;
        
        private string returnReceiverSmsField;
        
        private string salesCodeField;
        
        private string senderAdresField;
        
        private string senderCityIDField;
        
        private string senderDistrictIDField;
        
        private string senderMailField;
        
        private string senderNameField;
        
        private string senderNumberField;
        
        private string senderPhoneField;
        
        private string senderPostCodeField;
        
        private string senderSmsField;
        
        private string senderTCNoField;
        
        private string senderTaxNoField;
        
        private string senderUpperNumberField;
        
        private double valuePriceField;
        
        private bool valuePriceFieldSpecified;
        
        private System.Nullable<int> weightField;
        
        private bool weightFieldSpecified;
        
        private System.Nullable<int> widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string additionalDocuments {
            get {
                return this.additionalDocumentsField;
            }
            set {
                this.additionalDocumentsField = value;
                this.RaisePropertyChanged("additionalDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string additionalService {
            get {
                return this.additionalServiceField;
            }
            set {
                this.additionalServiceField = value;
                this.RaisePropertyChanged("additionalService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("context", IsNullable=true, Order=3)]
        public InvoceContent[] context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double desi {
            get {
                return this.desiField;
            }
            set {
                this.desiField = value;
                this.RaisePropertyChanged("desi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desiSpecified {
            get {
                return this.desiFieldSpecified;
            }
            set {
                this.desiFieldSpecified = value;
                this.RaisePropertyChanged("desiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string financialAdvisorNo {
            get {
                return this.financialAdvisorNoField;
            }
            set {
                this.financialAdvisorNoField = value;
                this.RaisePropertyChanged("financialAdvisorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string invoceNo {
            get {
                return this.invoceNoField;
            }
            set {
                this.invoceNoField = value;
                this.RaisePropertyChanged("invoceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double paymentConditionalPrice {
            get {
                return this.paymentConditionalPriceField;
            }
            set {
                this.paymentConditionalPriceField = value;
                this.RaisePropertyChanged("paymentConditionalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentConditionalPriceSpecified {
            get {
                return this.paymentConditionalPriceFieldSpecified;
            }
            set {
                this.paymentConditionalPriceFieldSpecified = value;
                this.RaisePropertyChanged("paymentConditionalPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string paymentmethod {
            get {
                return this.paymentmethodField;
            }
            set {
                this.paymentmethodField = value;
                this.RaisePropertyChanged("paymentmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> postalAccountNumber {
            get {
                return this.postalAccountNumberField;
            }
            set {
                this.postalAccountNumberField = value;
                this.RaisePropertyChanged("postalAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postalAccountNumberSpecified {
            get {
                return this.postalAccountNumberFieldSpecified;
            }
            set {
                this.postalAccountNumberFieldSpecified = value;
                this.RaisePropertyChanged("postalAccountNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string receiverAdres {
            get {
                return this.receiverAdresField;
            }
            set {
                this.receiverAdresField = value;
                this.RaisePropertyChanged("receiverAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string receiverAdres2 {
            get {
                return this.receiverAdres2Field;
            }
            set {
                this.receiverAdres2Field = value;
                this.RaisePropertyChanged("receiverAdres2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string receiverCityID {
            get {
                return this.receiverCityIDField;
            }
            set {
                this.receiverCityIDField = value;
                this.RaisePropertyChanged("receiverCityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string receiverCityID2 {
            get {
                return this.receiverCityID2Field;
            }
            set {
                this.receiverCityID2Field = value;
                this.RaisePropertyChanged("receiverCityID2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string receiverCountryId {
            get {
                return this.receiverCountryIdField;
            }
            set {
                this.receiverCountryIdField = value;
                this.RaisePropertyChanged("receiverCountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string receiverCountryId2 {
            get {
                return this.receiverCountryId2Field;
            }
            set {
                this.receiverCountryId2Field = value;
                this.RaisePropertyChanged("receiverCountryId2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string receiverMail {
            get {
                return this.receiverMailField;
            }
            set {
                this.receiverMailField = value;
                this.RaisePropertyChanged("receiverMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string receiverMail2 {
            get {
                return this.receiverMail2Field;
            }
            set {
                this.receiverMail2Field = value;
                this.RaisePropertyChanged("receiverMail2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string receiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
                this.RaisePropertyChanged("receiverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string receiverName2 {
            get {
                return this.receiverName2Field;
            }
            set {
                this.receiverName2Field = value;
                this.RaisePropertyChanged("receiverName2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string receiverPhone {
            get {
                return this.receiverPhoneField;
            }
            set {
                this.receiverPhoneField = value;
                this.RaisePropertyChanged("receiverPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string receiverPhone2 {
            get {
                return this.receiverPhone2Field;
            }
            set {
                this.receiverPhone2Field = value;
                this.RaisePropertyChanged("receiverPhone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string receiverPostCode {
            get {
                return this.receiverPostCodeField;
            }
            set {
                this.receiverPostCodeField = value;
                this.RaisePropertyChanged("receiverPostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string receiverPostCode2 {
            get {
                return this.receiverPostCode2Field;
            }
            set {
                this.receiverPostCode2Field = value;
                this.RaisePropertyChanged("receiverPostCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string receiverSms {
            get {
                return this.receiverSmsField;
            }
            set {
                this.receiverSmsField = value;
                this.RaisePropertyChanged("receiverSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string receiverSms2 {
            get {
                return this.receiverSms2Field;
            }
            set {
                this.receiverSms2Field = value;
                this.RaisePropertyChanged("receiverSms2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string reserved1 {
            get {
                return this.reserved1Field;
            }
            set {
                this.reserved1Field = value;
                this.RaisePropertyChanged("reserved1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string reserved10 {
            get {
                return this.reserved10Field;
            }
            set {
                this.reserved10Field = value;
                this.RaisePropertyChanged("reserved10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string reserved2 {
            get {
                return this.reserved2Field;
            }
            set {
                this.reserved2Field = value;
                this.RaisePropertyChanged("reserved2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string reserved3 {
            get {
                return this.reserved3Field;
            }
            set {
                this.reserved3Field = value;
                this.RaisePropertyChanged("reserved3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string reserved4 {
            get {
                return this.reserved4Field;
            }
            set {
                this.reserved4Field = value;
                this.RaisePropertyChanged("reserved4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string reserved5 {
            get {
                return this.reserved5Field;
            }
            set {
                this.reserved5Field = value;
                this.RaisePropertyChanged("reserved5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string reserved6 {
            get {
                return this.reserved6Field;
            }
            set {
                this.reserved6Field = value;
                this.RaisePropertyChanged("reserved6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string reserved7 {
            get {
                return this.reserved7Field;
            }
            set {
                this.reserved7Field = value;
                this.RaisePropertyChanged("reserved7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string reserved8 {
            get {
                return this.reserved8Field;
            }
            set {
                this.reserved8Field = value;
                this.RaisePropertyChanged("reserved8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string reserved9 {
            get {
                return this.reserved9Field;
            }
            set {
                this.reserved9Field = value;
                this.RaisePropertyChanged("reserved9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string returnReceiverAdres {
            get {
                return this.returnReceiverAdresField;
            }
            set {
                this.returnReceiverAdresField = value;
                this.RaisePropertyChanged("returnReceiverAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string returnReceiverCityID {
            get {
                return this.returnReceiverCityIDField;
            }
            set {
                this.returnReceiverCityIDField = value;
                this.RaisePropertyChanged("returnReceiverCityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public string returnReceiverCountryId {
            get {
                return this.returnReceiverCountryIdField;
            }
            set {
                this.returnReceiverCountryIdField = value;
                this.RaisePropertyChanged("returnReceiverCountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string returnReceiverDistrictID {
            get {
                return this.returnReceiverDistrictIDField;
            }
            set {
                this.returnReceiverDistrictIDField = value;
                this.RaisePropertyChanged("returnReceiverDistrictID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string returnReceiverMail {
            get {
                return this.returnReceiverMailField;
            }
            set {
                this.returnReceiverMailField = value;
                this.RaisePropertyChanged("returnReceiverMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string returnReceiverName {
            get {
                return this.returnReceiverNameField;
            }
            set {
                this.returnReceiverNameField = value;
                this.RaisePropertyChanged("returnReceiverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public string returnReceiverPhone {
            get {
                return this.returnReceiverPhoneField;
            }
            set {
                this.returnReceiverPhoneField = value;
                this.RaisePropertyChanged("returnReceiverPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string returnReceiverPostCode {
            get {
                return this.returnReceiverPostCodeField;
            }
            set {
                this.returnReceiverPostCodeField = value;
                this.RaisePropertyChanged("returnReceiverPostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public string returnReceiverSms {
            get {
                return this.returnReceiverSmsField;
            }
            set {
                this.returnReceiverSmsField = value;
                this.RaisePropertyChanged("returnReceiverSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string salesCode {
            get {
                return this.salesCodeField;
            }
            set {
                this.salesCodeField = value;
                this.RaisePropertyChanged("salesCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public string senderAdres {
            get {
                return this.senderAdresField;
            }
            set {
                this.senderAdresField = value;
                this.RaisePropertyChanged("senderAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public string senderCityID {
            get {
                return this.senderCityIDField;
            }
            set {
                this.senderCityIDField = value;
                this.RaisePropertyChanged("senderCityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public string senderDistrictID {
            get {
                return this.senderDistrictIDField;
            }
            set {
                this.senderDistrictIDField = value;
                this.RaisePropertyChanged("senderDistrictID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public string senderMail {
            get {
                return this.senderMailField;
            }
            set {
                this.senderMailField = value;
                this.RaisePropertyChanged("senderMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("senderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=54)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
                this.RaisePropertyChanged("senderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=55)]
        public string senderPhone {
            get {
                return this.senderPhoneField;
            }
            set {
                this.senderPhoneField = value;
                this.RaisePropertyChanged("senderPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=56)]
        public string senderPostCode {
            get {
                return this.senderPostCodeField;
            }
            set {
                this.senderPostCodeField = value;
                this.RaisePropertyChanged("senderPostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=57)]
        public string senderSms {
            get {
                return this.senderSmsField;
            }
            set {
                this.senderSmsField = value;
                this.RaisePropertyChanged("senderSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=58)]
        public string senderTCNo {
            get {
                return this.senderTCNoField;
            }
            set {
                this.senderTCNoField = value;
                this.RaisePropertyChanged("senderTCNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=59)]
        public string senderTaxNo {
            get {
                return this.senderTaxNoField;
            }
            set {
                this.senderTaxNoField = value;
                this.RaisePropertyChanged("senderTaxNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=60)]
        public string senderUpperNumber {
            get {
                return this.senderUpperNumberField;
            }
            set {
                this.senderUpperNumberField = value;
                this.RaisePropertyChanged("senderUpperNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public double valuePrice {
            get {
                return this.valuePriceField;
            }
            set {
                this.valuePriceField = value;
                this.RaisePropertyChanged("valuePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valuePriceSpecified {
            get {
                return this.valuePriceFieldSpecified;
            }
            set {
                this.valuePriceFieldSpecified = value;
                this.RaisePropertyChanged("valuePriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=62)]
        public System.Nullable<int> weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=63)]
        public System.Nullable<int> width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BarcodeInformation[] barcodeInformationField;
        
        private string folderNameField;
        
        private string passwordField;
        
        private string shipmentKindField;
        
        private string shipmentTypeField;
        
        private System.Nullable<int> userNameField;
        
        private bool userNameFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("barcodeInformation", IsNullable=true, Order=0)]
        public BarcodeInformation[] barcodeInformation {
            get {
                return this.barcodeInformationField;
            }
            set {
                this.barcodeInformationField = value;
                this.RaisePropertyChanged("barcodeInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string folderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
                this.RaisePropertyChanged("folderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string shipmentKind {
            get {
                return this.shipmentKindField;
            }
            set {
                this.shipmentKindField = value;
                this.RaisePropertyChanged("shipmentKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string shipmentType {
            get {
                return this.shipmentTypeField;
            }
            set {
                this.shipmentTypeField = value;
                this.RaisePropertyChanged("shipmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userNameSpecified {
            get {
                return this.userNameFieldSpecified;
            }
            set {
                this.userNameFieldSpecified = value;
                this.RaisePropertyChanged("userNameSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class HscodeList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string description_enField;
        
        private string description_trField;
        
        private string hscodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string description_en {
            get {
                return this.description_enField;
            }
            set {
                this.description_enField = value;
                this.RaisePropertyChanged("description_en");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string description_tr {
            get {
                return this.description_trField;
            }
            set {
                this.description_trField = value;
                this.RaisePropertyChanged("description_tr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string hscode {
            get {
                return this.hscodeField;
            }
            set {
                this.hscodeField = value;
                this.RaisePropertyChanged("hscode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://accept.ptt.gov.tr/xsd")]
    public partial class OutputHscodeList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> error_codeField;
        
        private bool error_codeFieldSpecified;
        
        private string error_descriptionField;
        
        private HscodeList[] hslistField;
        
        private int record_numberField;
        
        private bool record_numberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
                this.RaisePropertyChanged("error_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool error_codeSpecified {
            get {
                return this.error_codeFieldSpecified;
            }
            set {
                this.error_codeFieldSpecified = value;
                this.RaisePropertyChanged("error_codeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error_description {
            get {
                return this.error_descriptionField;
            }
            set {
                this.error_descriptionField = value;
                this.RaisePropertyChanged("error_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hslist", IsNullable=true, Order=2)]
        public HscodeList[] hslist {
            get {
                return this.hslistField;
            }
            set {
                this.hslistField = value;
                this.RaisePropertyChanged("hslist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int record_number {
            get {
                return this.record_numberField;
            }
            set {
                this.record_numberField = value;
                this.RaisePropertyChanged("record_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool record_numberSpecified {
            get {
                return this.record_numberFieldSpecified;
            }
            set {
                this.record_numberFieldSpecified = value;
                this.RaisePropertyChanged("record_numberSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHscodeList", WrapperNamespace="http://accept.ptt.gov.tr", IsWrapped=true)]
    public partial class getHscodeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accept.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTService.InputHscodeList input;
        
        public getHscodeListRequest() {
        }
        
        public getHscodeListRequest(MVCProject.WebUI.PTTService.InputHscodeList input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHscodeListResponse", WrapperNamespace="http://accept.ptt.gov.tr", IsWrapped=true)]
    public partial class getHscodeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accept.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTService.OutputHscodeList @return;
        
        public getHscodeListResponse() {
        }
        
        public getHscodeListResponse(MVCProject.WebUI.PTTService.OutputHscodeList @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadData", WrapperNamespace="http://accept.ptt.gov.tr", IsWrapped=true)]
    public partial class loadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accept.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTService.Input input;
        
        public loadDataRequest() {
        }
        
        public loadDataRequest(MVCProject.WebUI.PTTService.Input input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadDataResponse", WrapperNamespace="http://accept.ptt.gov.tr", IsWrapped=true)]
    public partial class loadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://accept.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTService.Output @return;
        
        public loadDataResponse() {
        }
        
        public loadDataResponse(MVCProject.WebUI.PTTService.Output @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoadPortTypeChannel : MVCProject.WebUI.PTTService.LoadPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadPortTypeClient : System.ServiceModel.ClientBase<MVCProject.WebUI.PTTService.LoadPortType>, MVCProject.WebUI.PTTService.LoadPortType {
        
        public LoadPortTypeClient() {
        }
        
        public LoadPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCProject.WebUI.PTTService.getHscodeListResponse MVCProject.WebUI.PTTService.LoadPortType.getHscodeList(MVCProject.WebUI.PTTService.getHscodeListRequest request) {
            return base.Channel.getHscodeList(request);
        }
        
        public MVCProject.WebUI.PTTService.OutputHscodeList getHscodeList(MVCProject.WebUI.PTTService.InputHscodeList input) {
            MVCProject.WebUI.PTTService.getHscodeListRequest inValue = new MVCProject.WebUI.PTTService.getHscodeListRequest();
            inValue.input = input;
            MVCProject.WebUI.PTTService.getHscodeListResponse retVal = ((MVCProject.WebUI.PTTService.LoadPortType)(this)).getHscodeList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.getHscodeListResponse> MVCProject.WebUI.PTTService.LoadPortType.getHscodeListAsync(MVCProject.WebUI.PTTService.getHscodeListRequest request) {
            return base.Channel.getHscodeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.getHscodeListResponse> getHscodeListAsync(MVCProject.WebUI.PTTService.InputHscodeList input) {
            MVCProject.WebUI.PTTService.getHscodeListRequest inValue = new MVCProject.WebUI.PTTService.getHscodeListRequest();
            inValue.input = input;
            return ((MVCProject.WebUI.PTTService.LoadPortType)(this)).getHscodeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCProject.WebUI.PTTService.loadDataResponse MVCProject.WebUI.PTTService.LoadPortType.loadData(MVCProject.WebUI.PTTService.loadDataRequest request) {
            return base.Channel.loadData(request);
        }
        
        public MVCProject.WebUI.PTTService.Output loadData(MVCProject.WebUI.PTTService.Input input) {
            MVCProject.WebUI.PTTService.loadDataRequest inValue = new MVCProject.WebUI.PTTService.loadDataRequest();
            inValue.input = input;
            MVCProject.WebUI.PTTService.loadDataResponse retVal = ((MVCProject.WebUI.PTTService.LoadPortType)(this)).loadData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.loadDataResponse> MVCProject.WebUI.PTTService.LoadPortType.loadDataAsync(MVCProject.WebUI.PTTService.loadDataRequest request) {
            return base.Channel.loadDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCProject.WebUI.PTTService.loadDataResponse> loadDataAsync(MVCProject.WebUI.PTTService.Input input) {
            MVCProject.WebUI.PTTService.loadDataRequest inValue = new MVCProject.WebUI.PTTService.loadDataRequest();
            inValue.input = input;
            return ((MVCProject.WebUI.PTTService.LoadPortType)(this)).loadDataAsync(inValue);
        }
    }
}
