//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.WebUI.PTTTrack {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Tracking.ptt.gov.tr", ConfigurationName="PTTTrack.PttTrackPortType")]
    public interface PttTrackPortType {
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Tracking", ReplyAction="urn:TrackingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MVCProject.WebUI.PTTTrack.TrackingResponse Tracking(MVCProject.WebUI.PTTTrack.TrackingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Tracking", ReplyAction="urn:TrackingResponse")]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTTrack.TrackingResponse> TrackingAsync(MVCProject.WebUI.PTTTrack.TrackingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Tracking.ptt.gov.tr/xsd")]
    public partial class Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Tracking.ptt.gov.tr/xsd")]
    public partial class TrackingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barkodNoField;
        
        private string gonderi_durum_aciklamaField;
        
        private string gonderi_durum_idField;
        
        private string ilField;
        
        private string islem_saatiField;
        
        private string islem_tarihiField;
        
        private string merkezField;
        
        private string subeField;
        
        private string teslim_alanField;
        
        private string ulke_adField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string barkodNo {
            get {
                return this.barkodNoField;
            }
            set {
                this.barkodNoField = value;
                this.RaisePropertyChanged("barkodNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string gonderi_durum_aciklama {
            get {
                return this.gonderi_durum_aciklamaField;
            }
            set {
                this.gonderi_durum_aciklamaField = value;
                this.RaisePropertyChanged("gonderi_durum_aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string gonderi_durum_id {
            get {
                return this.gonderi_durum_idField;
            }
            set {
                this.gonderi_durum_idField = value;
                this.RaisePropertyChanged("gonderi_durum_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string il {
            get {
                return this.ilField;
            }
            set {
                this.ilField = value;
                this.RaisePropertyChanged("il");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string islem_saati {
            get {
                return this.islem_saatiField;
            }
            set {
                this.islem_saatiField = value;
                this.RaisePropertyChanged("islem_saati");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string islem_tarihi {
            get {
                return this.islem_tarihiField;
            }
            set {
                this.islem_tarihiField = value;
                this.RaisePropertyChanged("islem_tarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string merkez {
            get {
                return this.merkezField;
            }
            set {
                this.merkezField = value;
                this.RaisePropertyChanged("merkez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string sube {
            get {
                return this.subeField;
            }
            set {
                this.subeField = value;
                this.RaisePropertyChanged("sube");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string teslim_alan {
            get {
                return this.teslim_alanField;
            }
            set {
                this.teslim_alanField = value;
                this.RaisePropertyChanged("teslim_alan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ulke_ad {
            get {
                return this.ulke_adField;
            }
            set {
                this.ulke_adField = value;
                this.RaisePropertyChanged("ulke_ad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Tracking.ptt.gov.tr/xsd")]
    public partial class Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string etgb_DateField;
        
        private string etgb_NoField;
        
        private string outCodeField;
        
        private string outDescField;
        
        private TrackingInfo[] trackingInfField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string etgb_Date {
            get {
                return this.etgb_DateField;
            }
            set {
                this.etgb_DateField = value;
                this.RaisePropertyChanged("etgb_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string etgb_No {
            get {
                return this.etgb_NoField;
            }
            set {
                this.etgb_NoField = value;
                this.RaisePropertyChanged("etgb_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string outCode {
            get {
                return this.outCodeField;
            }
            set {
                this.outCodeField = value;
                this.RaisePropertyChanged("outCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string outDesc {
            get {
                return this.outDescField;
            }
            set {
                this.outDescField = value;
                this.RaisePropertyChanged("outDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("trackingInf", IsNullable=true, Order=4)]
        public TrackingInfo[] trackingInf {
            get {
                return this.trackingInfField;
            }
            set {
                this.trackingInfField = value;
                this.RaisePropertyChanged("trackingInf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Tracking", WrapperNamespace="http://Tracking.ptt.gov.tr", IsWrapped=true)]
    public partial class TrackingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Tracking.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTTrack.Input inp;
        
        public TrackingRequest() {
        }
        
        public TrackingRequest(MVCProject.WebUI.PTTTrack.Input inp) {
            this.inp = inp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TrackingResponse", WrapperNamespace="http://Tracking.ptt.gov.tr", IsWrapped=true)]
    public partial class TrackingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Tracking.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MVCProject.WebUI.PTTTrack.Output @return;
        
        public TrackingResponse() {
        }
        
        public TrackingResponse(MVCProject.WebUI.PTTTrack.Output @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PttTrackPortTypeChannel : MVCProject.WebUI.PTTTrack.PttTrackPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PttTrackPortTypeClient : System.ServiceModel.ClientBase<MVCProject.WebUI.PTTTrack.PttTrackPortType>, MVCProject.WebUI.PTTTrack.PttTrackPortType {
        
        public PttTrackPortTypeClient() {
        }
        
        public PttTrackPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PttTrackPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PttTrackPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PttTrackPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCProject.WebUI.PTTTrack.TrackingResponse MVCProject.WebUI.PTTTrack.PttTrackPortType.Tracking(MVCProject.WebUI.PTTTrack.TrackingRequest request) {
            return base.Channel.Tracking(request);
        }
        
        public MVCProject.WebUI.PTTTrack.Output Tracking(MVCProject.WebUI.PTTTrack.Input inp) {
            MVCProject.WebUI.PTTTrack.TrackingRequest inValue = new MVCProject.WebUI.PTTTrack.TrackingRequest();
            inValue.inp = inp;
            MVCProject.WebUI.PTTTrack.TrackingResponse retVal = ((MVCProject.WebUI.PTTTrack.PttTrackPortType)(this)).Tracking(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCProject.WebUI.PTTTrack.TrackingResponse> MVCProject.WebUI.PTTTrack.PttTrackPortType.TrackingAsync(MVCProject.WebUI.PTTTrack.TrackingRequest request) {
            return base.Channel.TrackingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCProject.WebUI.PTTTrack.TrackingResponse> TrackingAsync(MVCProject.WebUI.PTTTrack.Input inp) {
            MVCProject.WebUI.PTTTrack.TrackingRequest inValue = new MVCProject.WebUI.PTTTrack.TrackingRequest();
            inValue.inp = inp;
            return ((MVCProject.WebUI.PTTTrack.PttTrackPortType)(this)).TrackingAsync(inValue);
        }
    }
}
